extends Node

signal enemy_killed(enemy_data: Dictionary)
signal enemy_spawned(enemy: Node)
signal room_entered(room_id: int)
signal room_cleared(room_id: int)
signal all_enemies_dead()
signal item_picked_up(item_data: Resource)
signal item_equipped(slot: String, item_data: Resource)
signal item_unequipped(slot: String, item_data: Resource)
signal gold_changed(new_amount: int)
signal player_damaged(amount: int, current_hp: int)
signal player_healed(amount: int, current_hp: int)
signal player_died()
signal ability_used(ability_index: int)
signal ability_cooldown_started(ability_index: int, duration: float)
signal floor_completed(floor_number: int)
signal boss_defeated(boss_id: String)
signal door_transition_requested(door: Node)
signal meta_currency_gained(amount: int)
signal item_compare_requested(new_item: Resource, old_item: Resource)
signal shop_opened(items: Array)
signal shop_closed()
